[package]
name = "auto-waifu"
version = "0.1.0"
authors = ["Drew Hutton <drew.hutton@pm.me>"]
edition = "2018"

[dependencies]
base64 = "0.12.0"
image = "0.23.4"
headless_chrome = "0.9.0"
failure = "0.1.7"
openssl = { version = "0.10", features = ["vendored"] }
